apiVersion: v1
kind: Secret
metadata:
  name: wechat
type: Opaque #
stringData:
  #appid: <APP_ID> 最好使用Jenkins 声明系统环境变量，之后在这里使用环境变量
  appid: wx851020fe449a84e2
  #appsecret: <APP_KEY>
  appsecret: 26c95bc945fd0d7ccf7c473ef5a5e7f8